import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "@/context/auth";
import AuthButtons from "@/components/auth-buttons";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import Image from "next/image";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AuthProvider>
          <nav className="bg-red-600 text-white p-5 h-14 flex items-center justify-between z-10 relative">
            <Link
              href="/"
              className="flex gap-3 items-center"
            >
              <Image
                src="/SCCC.BK.svg"
                alt="INSEE Logo"
                width={40}
                height={40}
                className="w-10 h-10 filter brightness-0 invert"
              />
              <span className="text-2xl tracking-widest uppercase font-semibold">INSEE Safety</span>
            </Link>
            <ul className="flex gap-6 items-center">
              <li>
                <Link
                  href="/Machine/vn/Lifting/CANT-1"
                  className="uppercase tracking-widest hover:underline"
                >
                  1st inspection
                </Link>
              </li>
              <li>
                <AuthButtons />
              </li>
            </ul>
          </nav>
          {children}
          <Toaster richColors closeButton />
        </AuthProvider>
      </body>
    </html>
  );
}
